sudo: required
dist: xenial
language: rust
install:
- "echo ubuntu-mirror: $UBUNTU_MIRROR > ~/.vagga.yaml"
- "echo alpine-mirror: $ALPINE_MIRROR >> ~/.vagga.yaml"
- "sudo apt-get install musl-tools"
- "rustup target add x86_64-unknown-linux-musl"
- "[[ -n $TEST_CASES ]] && cargo build --target x86_64-unknown-linux-musl && cp ./target/x86_64-unknown-linux-musl/debug/vagga ."
- "[[ -n $TEST_CASES ]] && ./vagga _build test"
env:
  global:
  - UBUNTU_MIRROR=http://mirrors.us.kernel.org/ubuntu/
  - ALPINE_MIRROR=http://mirrors.gigenet.com/alpinelinux/
  - VAGGA_VERSION=$(git describe)
  matrix:
    - TEST_CASES=
    - TEST_CASES=tests/alpine.bats
    - TEST_CASES="tests/ubuntu.bats tests/ubuntu_release.bats"
    - TEST_CASES=tests/npm.bats
    - TEST_CASES=tests/pip.bats
    - TEST_CASES=tests/gem_bundler.bats
    - TEST_CASES=tests/composer.bats
    - TEST_CASES="tests/badcmd.bats tests/completion.bats tests/copy.bats tests/generic.bats tests/image.bats tests/inheritance.bats tests/prerequisites.bats tests/readonly.bats tests/uidmap.bats tests/vcs.bats tests/version.bats"
script:
- "[[ -z $TEST_CASES ]] && cargo test"
- "[[ -n $TEST_CASES ]] && ./vagga -eUBUNTU_MIRROR -eALPINE_MIRROR test --tap $TEST_CASES"
